# AWS DataBase Push Back

In [48]:
import pandas as pd
from sqlalchemy import create_engine



# Replace with your connection details
host = "youtubedb.cj2yoywsiz3x.ap-south-1.rds.amazonaws.com"
port = "3306"  # Default port for MYSQL
database = "youtubedb"
username = "admin"
password = "database"

# Create the connection string (URL format) -> mysql
engine_string = f"mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}"

# Create the SQLAlchemy engine
engine = create_engine(engine_string)

In [49]:
# Fetch data from the database
def fetch_data():
    query = "SELECT * FROM youtube_cleaned_data"  # Adjust the query as needed
    return pd.read_sql(query, engine)

# Load the data
df = fetch_data()

In [50]:
df

,video_id,channelTitle,title,description,tags,publishedAt,thumbnails,viewCount,likeCount,duration,thumbnail_url
0,QUoJq_XuRb0,National Geographic,Festival Flip! | Epcot Becoming Episode 5 | Na...,Four unique festivals take place at EPCOT® eve...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-16T14:00:13Z,{'default': {'url': 'https://i.ytimg.com/vi/QU...,1769.0,153.0,PT5M16S,https://i.ytimg.com/vi/QUoJq_XuRb0/hqdefault.jpg
1,jtrFTHlUJ5Q,National Geographic,Investigating Cyber Pirates (Full Episode) | T...,Mariana is on a mission to understand how pers...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-15T15:00:44Z,{'default': {'url': 'https://i.ytimg.com/vi/jt...,40051.0,1014.0,PT44M25S,https://i.ytimg.com/vi/jtrFTHlUJ5Q/hqdefault.jpg
2,pA2erVpBOQw,National Geographic,Meet Aldo Kane | Ocean Xplorers,Join the #OceanXplorers Operations and Surviva...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-15T12:00:56Z,{'default': {'url': 'https://i.ytimg.com/vi/pA...,5764.0,372.0,PT49S,https://i.ytimg.com/vi/pA2erVpBOQw/hqdefault.jpg
3,y5VqYqYVwn0,National Geographic,Paid Content for The Maine Office of Tourism. ...,Paid Content for The Maine Office of Tourism. ...,"['maine tourism', 'national geographic', 'main...",2024-08-14T15:01:10Z,{'default': {'url': 'https://i.ytimg.com/vi/y5...,4956.0,279.0,PT50S,https://i.ytimg.com/vi/y5VqYqYVwn0/hqdefault.jpg
4,SLmWY_ycFUA,National Geographic,Uncovering the Secrets of the Sun to Save Plan...,National Geographic reveals a bright new dawn ...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-11T15:00:19Z,{'default': {'url': 'https://i.ytimg.com/vi/SL...,17380.0,435.0,PT44M25S,https://i.ytimg.com/vi/SLmWY_ycFUA/hqdefault.jpg
...,...,...,...,...,...,...,...,...,...,...,...
13424,jItJ2XMR7QA,Firstpost,Will Governments Ask Olympic Winners To Pay Ta...,Will Governments Ask Olympic Winners To Pay Ta...,"['firstpost', 'firstpost sports', 'sports firs...",2024-08-14T14:56:35Z,{'default': {'url': 'https://i.ytimg.com/vi/jI...,10413.0,267.0,PT33S,https://i.ytimg.com/vi/jItJ2XMR7QA/hqdefault.jpg
13425,kfCYiH5PJNw,Firstpost,Will Olympic Medalists Pay Taxes To Government...,Will Olympic Medalists Pay Taxes To Government...,"['firstpost', 'firstpost sports', 'sports firs...",2024-08-14T14:55:00Z,{'default': {'url': 'https://i.ytimg.com/vi/kf...,18338.0,129.0,PT5M53S,https://i.ytimg.com/vi/kfCYiH5PJNw/hqdefault.jpg
13426,fi_Yyb74wtw,Firstpost,Taiwan Welcomes Olympic Athletes With Fighter ...,Taiwan Welcomes Olympic Athletes With Fighter ...,"['firstpost', 'firstpost sports', 'sports firs...",2024-08-14T14:53:25Z,{'default': {'url': 'https://i.ytimg.com/vi/fi...,11570.0,399.0,PT26S,https://i.ytimg.com/vi/fi_Yyb74wtw/hqdefault.jpg
13427,Gbf0YMYnuIs,Firstpost,"Imane Khelif Adds Elon Musk & JK Rowling in ""H...","Imane Khelif Adds Elon Musk & JK Rowling in ""H...","['firstpost', 'firstpost sports', 'sports firs...",2024-08-14T14:45:01Z,{'default': {'url': 'https://i.ytimg.com/vi/Gb...,7538.0,64.0,PT7M31S,https://i.ytimg.com/vi/Gbf0YMYnuIs/hqdefault.jpg
13428,JKbsJyyBrlI,Firstpost,"Vinicius Offered $1.1 Billion By Saudi, Real M...","Vinicius Offered $1.1 Billion By Saudi, Real M...","['firstpost', 'firstpost sports', 'sports firs...",2024-08-14T14:27:08Z,{'default': {'url': 'https://i.ytimg.com/vi/JK...,11161.0,174.0,PT7M29S,https://i.ytimg.com/vi/JKbsJyyBrlI/hqdefault.jpg

# Machine Learning Unsupervised Clustering

In [4]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (1.5.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.0.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.14.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [51]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
# Sample initialization with adjusted parameters
vectorizer = TfidfVectorizer(stop_words='english')

# Fit and transform the data
tag_vectors = vectorizer.fit_transform(df['tags'])  # Assuming 'tags' column contains text data

In [53]:
tag_normalization = tag_vectors.toarray()

tag_normalization

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
# Choose the number of clusters (k) based on your data and requirements
k = 16 # Example number of clusters
kmeans = KMeans(n_clusters=k,random_state=10,n_init=10)
kmeans.fit(tag_normalization)

# Add the cluster labels to the DataFrame
df['cluster'] = kmeans.labels_

In [55]:
df['cluster'].value_counts()

cluster
2     10458
9       594
0       269
15      206
1       204
14      204
4       200
7       188
5       180
10      173
12      152
13      132
8       124
6       122
3       119
11      104
Name: count, dtype: int64

In [56]:
df.head()

,video_id,channelTitle,title,description,tags,publishedAt,thumbnails,viewCount,likeCount,duration,thumbnail_url,cluster
0,QUoJq_XuRb0,National Geographic,Festival Flip! | Epcot Becoming Episode 5 | Na...,Four unique festivals take place at EPCOT® eve...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-16T14:00:13Z,{'default': {'url': 'https://i.ytimg.com/vi/QU...,1769.0,153.0,PT5M16S,https://i.ytimg.com/vi/QUoJq_XuRb0/hqdefault.jpg,2
1,jtrFTHlUJ5Q,National Geographic,Investigating Cyber Pirates (Full Episode) | T...,Mariana is on a mission to understand how pers...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-15T15:00:44Z,{'default': {'url': 'https://i.ytimg.com/vi/jt...,40051.0,1014.0,PT44M25S,https://i.ytimg.com/vi/jtrFTHlUJ5Q/hqdefault.jpg,2
2,pA2erVpBOQw,National Geographic,Meet Aldo Kane | Ocean Xplorers,Join the #OceanXplorers Operations and Surviva...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-15T12:00:56Z,{'default': {'url': 'https://i.ytimg.com/vi/pA...,5764.0,372.0,PT49S,https://i.ytimg.com/vi/pA2erVpBOQw/hqdefault.jpg,2
3,y5VqYqYVwn0,National Geographic,Paid Content for The Maine Office of Tourism. ...,Paid Content for The Maine Office of Tourism. ...,"['maine tourism', 'national geographic', 'main...",2024-08-14T15:01:10Z,{'default': {'url': 'https://i.ytimg.com/vi/y5...,4956.0,279.0,PT50S,https://i.ytimg.com/vi/y5VqYqYVwn0/hqdefault.jpg,2
4,SLmWY_ycFUA,National Geographic,Uncovering the Secrets of the Sun to Save Plan...,National Geographic reveals a bright new dawn ...,"['national geographic', 'nat geo', 'natgeo', '...",2024-08-11T15:00:19Z,{'default': {'url': 'https://i.ytimg.com/vi/SL...,17380.0,435.0,PT44M25S,https://i.ytimg.com/vi/SLmWY_ycFUA/hqdefault.jpg,2

In [24]:
score = silhouette_score(tag_normalization, kmeans.labels_)

score

np.float64(0.20561414277374154)

In [46]:
def recommend_videos(user_input, df, tag_vectors, vectorizer,top_n=500):
    # Transform the user input into a vector
    user_vector = vectorizer.transform([user_input])
    # Calculate cosine similarity between the user vector and video vectors
    similarities = cosine_similarity(user_vector, tag_vectors).flatten()

    # Get the indices of the top N most similar videos
    top_indices = similarities.argsort()[top_n:][::-1]
  


    # Retrieve the video IDs, channel titles, and titles of the top recommendations
    recommendations = df.iloc[top_indices][['video_id', 'channelTitle', 'title']]
    unique_recommendations = recommendations.drop_duplicates(subset='channelTitle')

    return unique_recommendations

In [16]:
# Example user input
user_input = input('Enter your video name: ')

# Get recommendations
unique_recommendations = recommend_videos(user_input, df, tag_vectors, vectorizer)

# Print the recommendation
unique_recommendations

,video_id,channelTitle,title,thumbnails
5976,AVBUFvJtiLM,ABC News,Timelapse shows moon setting into glowing auro...,{'default': {'url': 'https://i.ytimg.com/vi/AV...
5819,2_AbGW7m9lI,BBC News,Interim government to run Bangladesh after PM ...,{'default': {'url': 'https://i.ytimg.com/vi/2_...
4832,W9w_uj0Pdek,NDTV,Tamil Nadu Rain | Heavy Rain Lashes Parts Of M...,{'default': {'url': 'https://i.ytimg.com/vi/W9...
6808,3QDFzfRqyRE,Fox News,VP candidate Gov. Tim Walz delivers remarks in...,{'default': {'url': 'https://i.ytimg.com/vi/3Q...
11358,A3ixCgLYWw4,Financial Times,Petrostates risk losing trillions as world tur...,{'default': {'url': 'https://i.ytimg.com/vi/A3...
...,...,...,...,...
8036,-tb0Ur5_pjU,Jenny's Lectures CS IT,Return Multiple values from a Function |Multip...,{'default': {'url': 'https://i.ytimg.com/vi/-t...
8576,0Mi0miIN6tA,TED,How to Imagine a Better Future for Democracy |...,{'default': {'url': 'https://i.ytimg.com/vi/0M...
7495,F2Q5vXt4xic,Mrwhosetheboss,Turn ANY object into a SPEAKER!,{'default': {'url': 'https://i.ytimg.com/vi/F2...
7515,FwjshZCtUS0,OneDirectionVEVO,One Direction - Never Enough (Audio),{'default': {'url': 'https://i.ytimg.com/vi/Fw...
7627,OmvU0Jk88Cg,One Direction,One Direction - Between Us Fragrance Ad,{'default': {'url': 'https://i.ytimg.com/vi/Om...

#Convert Pickle File

In [57]:
df.to_pickle('Pickle_file')